### ISSUE TITLE
五十万条题库

### ISSUE THREAD

**Issue by Pantyhose-X** [Ivysauro/AnkiNPEE#1]
可以 添加 个牌组 33iq五十万条题库
侦探推理 逻辑思维 谜语大全 脑筋急转弯 趣味益智 图形视觉 数学天地 知识百科 决策判断 棋牌世界 对联大全 
https://www.33iq.com/question/1.html              question/1.html      1 是题页
https://www.33iq.com/question/518279.html
这有一个python 爬虫脚本 https://github.com/reece15/tiku_spider

**Comment by Ivysauro** [comment]
很不错 但是没空😮‍💨
